RegistrationViaTelegram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tgbot_manage.urls", namespace="tgbot")),
]

tgbot_manage/urls.py
from django.urls import path

from .views import (login_view)

urlpatterns = [
    path("", login_view, name="login"),

]

app_name = "tgbot_manager"

tgbot_manage/models.py
from django.db import models

# Create your models here.

tgbot_manage/views.py
from django.shortcuts import render

from tgbot_manage.airtable import data_in_airtable


def login_view(request):
    if request.method == "GET":
        return render(request, "login.html")
    if request.method == "POST":
        data_of_users = data_in_airtable()
        username = request.POST["username"]
        password = request.POST["password"]
        url_user_tg_account = f"https://t.me/{username}"

        if username in data_of_users:
            data_of_user = data_of_users[username]
            if data_of_user["password"] == password:
                context = {
                    "password": password,
                    "username": username,
                    "full_name": f"{data_of_user['first_name']} {data_of_user['last_name']}",
                    "id": f"{data_of_user['id']}",
                    "url_user_tg_account": url_user_tg_account,
                }

                return render(request, "index.html", context=context)

        error_contex = {
                "errors": "Invalid credentials"
            }

        return render(request, "login.html", context=error_contex)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous">

</head>
<body style="margin: 60px 130px">

    <h1>Home Page</h1>
    <p>Welcome to Home Page!</p>
    <hr>
    <h2>Dynamic content</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae dolorum id saepe voluptate. Accusamus accusantium aliquam assumenda, dignissimos doloremque ea eaque esse exercitationem expedita necessitatibus non optio perferendis perspiciatis porro quasi quibusdam sed tempore temporibus tenetur voluptas. Blanditiis commodi dolore dolores esse, facere, id in ipsum laudantium magnam modi neque numquam odit pariatur perferendis praesentium provident veritatis. Doloribus enim obcaecati sequi. A accusantium alias asperiores aspernatur commodi cum deleniti deserunt dignissimos dolores eaque error esse eum facilis hic id incidunt iure laborum magnam maiores minus necessitatibus odit officia omnis perferendis placeat porro possimus praesentium quaerat quas qui quo, tempora, tenetur ullam ut velit vero voluptate. A animi asperiores aspernatur, delectus dolor eaque esse explicabo facere facilis laudantium libero molestiae mollitia numquam odio, officiis quas quisquam repudiandae, saepe sequi unde! Asperiores doloremque doloribus ducimus illum iste laudantium nulla rem reprehenderit, rerum voluptatibus? Ad aperiam, atque distinctio doloremque inventore obcaecati quas qui?</p>

    <hr>
    <p><strong>Information about user</strong></p>

    <ul>
        <li><strong>Username: </strong>{{ username }}</li>
        <li><strong>Full name: </strong>{{ full_name }}</li>
        <li><strong>Id: </strong>{{ id }}</li>
    </ul>

    <hr>
    <button style="margin-right: 30px" type="submit" class="btn btn-primary">
        <a style="color: aliceblue" href={{url_user_tg_account}}>Go to Telegram</a>
    </button>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous">
</head>


<body>
{% load crispy_forms_filters %}
{% csrf_token %}
<div style="margin: 150px">
    <h1>Login</h1>

    {% if errors  %}
        <p style="color: red">{{ errors }}</p>
    {% endif %}

    <form class="" method="post" action="{% url 'tgbot:login' %}">
        {% csrf_token %}

        <div class="form-group">
    <lable>Username:
        <input type="text" name="username" class="form-control">
    </lable>

        </div>
          <div class="form-group">
    <lable>Password:
        <input type="password" name="password" class="form-control">
    </lable>
          </div>

    <input style="margin-left:30px" type="submit" value="Login" class="btn btn-success" />

        <div style="margin-top: 50px">
        <p style="margin: 20px">
           If you don't have an account yet, you can always create in Telegram))
        </p>
        </div>
        <button style="margin-right: 30px" type="submit" class="btn btn-warning">
    <a style="text-decoration: none" href="https://t.me/registration23_bot">Create account</a>
        </button>
    </form>
</div>
</body>